os:
  - osx
osx_image: xcode8.2
xcode_sdk: iPhone 7 (10.2)
language: objective-c
before_install:
 - rvm install 2.3.3
 - rvm use 2.3.3
 - gem install bundler
 - bundle install
# cache: cocoapods
script:
 - pwd
 - xcrun simctl list
 - bundle exec fastlane test
